#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  # -- image repository
  repository: goalert/goalert
  # -- image tag
  pullPolicy: IfNotPresent
  # -- image pull policy
  tag: 0.28.0

# -- environment variables. See more environment variables in the [thelounge documentation](https://hub.docker.com/r/linuxserver/thelounge)
# @default -- See below
env:
  # -- Set the container timezone
  GOALERT_DATA_ENCRYPTION_KEY: super-awesome-secret-key
  GOALERT_DB_URL: postgres://goalert@localhost/goalert

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 8081

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false
    # If you use https as the backend, you need to enable tell your ingress
    # annotations:
    #  nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    #  ingress.kubernetes.io/protocol: https

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  config:
    enabled: false
    mountPath: /config
